### ISSUE TITLE
license prevents collaboration & community involvement

### ISSUE THREAD

**Issue by mozfreddyb** [PortSwigger/xss-cheatsheet-data#2]
I'm unsure if your license file has been carefully chosen, but I don't think the community can make good use of the cheat sheet (e.g., in research, in tools). I see that you explicitly do not want derivative work. Would you be so kind and expand on that?

I'm feel deterred from contributing with this existing setup.

I personally don't think that copyright is a good mechanism to convey ownership and maintenance. I'm really happy that we have well-known researchers coming up as new maintainers of good XSS resources, and I really want it to go well. I event want to support you (see pull request #1 ;)).

But I'm also under the impression that some of your XSS vectors are not original work, which makes the copyright thing just more smelly.

**Comment by albinowax** [comment]
I wrote this license and I'm not a copyright lawyer so maybe I got something wrong, but here's the rational.

In the past, we've had trouble with people copy+pasting our research output and claiming it as theirs without citing us or even making any improvements themselves. For example, https://twitter.com/albinowax/status/1065609561577582592

The vast majority of our research is published directly on our site without any kind of license; and we've chosen this license to try and ensure that from a legal perspective, this cheat sheet data is protected to exactly the same degree. I don't see anyone claiming that nobody can use HTTP Desync Attacks in their research just because I didn't stick a creative commons license on the whitepaper, so I'm not sure why this dataset should be any different.

We make it 100% explicit that the original vectors are not all ours - all vector authors (to the best of a knowledge) are cited here: https://portswigger.net/web-security/cross-site-scripting/cheat-sheet#credits

We're open to suggestions for rephrasing the license provided it still prohibits people from creating derivative work.

**Comment by mozfreddyb** [comment]
> In the past, we've had trouble with people copy+pasting our research output and claiming it as theirs without citing us or even making any improvements themselves. For example, https://twitter.com/albinowax/status/1065609561577582592
> 

I think this only emphasizes the value of your research. Don't they say imitation is the sincerest form of flattery?
However, I do understand how annoying this is and I understand that you don't want people buying copy-products. But I also don't think that this existing LICENSE is a useful stop gap. I'd argue that this is bad for the community and has no impact for anyone who wants to "cheaply" benefit from this joint work here.

> We make it 100% explicit that the original vectors are not all ours - all vector authors (to the best of a knowledge) are cited here: https://portswigger.net/web-security/cross-site-scripting/cheat-sheet#credits

Well if the _data_ is not yours, why do you claim so in the LICENSE file of the _data_ repository :confused: 

> 
> We're open to suggestions for rephrasing the license provided it still prohibits people from creating derivative work.

I suggest you use a CC-BY-SA or a CC-BY-ND license. 
The "BY" part could say "PortSwigger XSS CheatSheet Contributors" or spell out the names (I know, I know :))

Personally, I'd prefer the Share-Alike that allows people to pick this up, in case this dies the eventual death of low-maintenance just like all the other XSS cheat sheets before you.

If you choose the No-Derivatives license, we'd have to trust this doesn't happen (which would be a welcoming change, really).


P.S: IANAL

**Comment by albinowax** [comment]
We're not trying to claiming copyright over every individual vectors, that would be crazy. The copyright is on the overall dataset which has been constructed and curated by PortSwigger. Even if this is a valid issue, I don't see how deploying CC-BY-ND does anything to address it?

**Comment by mozfreddyb** [comment]
> We're not trying to claiming copyright over every individual vectors, that would be crazy. 

That's what the LICENSE file reads to me.
If you deployed CC-BY-ND saying "Made by the PortSwigger XSS Cheat Contributors" you'd stop doing so.

**Comment by albinowax** [comment]
Closing this as we don't plan to take any action here.
