### ISSUE TITLE
Impossible Lab: innerHTML context but no equals allowed - exploitable if AngularJS present

### ISSUE THREAD

**Issue by wtconsulting** [PortSwigger/xss-cheatsheet-data#36]
`You have a site that processes the query string and URL decodes the parameters but splits on the equals then assigns to innerHTML. In this context <script> doesn't work and we can't use = to create an event.`

Hey all - Just throwing it out there but:

In this case of innerHTML no equals, you can still get full CSS context because you can inject style tag and CSS. Using CSS at-import you can grab your own style sheet and start doing all kinds of things.

Example passing in style to innerHTML. Pass `<style>*{color: red;}</style>` as the x value below
[Example CSS context](https://portswigger-labs.net/impossible-labs/innerHTML-no-equals.php?x=%3Cstyle%3E*{color:%20red;}%3C/style%3E) You probably want to use the @import so that you have equals available in both the CSS and any JS you pass in.

But maybe more importantly (and its a big if, but with 4 million sites still using it not unheard of...), you can actually then get full JS context using something as simple as the following _**if the site is using AngularJS**_: 

` h1:after {
           content: '{{constructor.constructor('alert(1)')()}}';
 }  `

Example: [http://tpcg.io/_W2NR74](https://t.co/Vbt8oTAfqH) using [Mario Heiderich](https://twitter.com/cure53berlin) last escape.

Smuggling the Angular through the CSS isn't strictly necessary when doing something trivial like popping an alert, but to do anything more serious you would probably need the equals available. 

Also just conversation - I think even just the CSS context can be super dangerous. If there are two random inputs on the page anywhere, they could be absolutely positioned and styled to steal username password creds (using CSS only key logging). Text ("Please login again to continue" or whatever) can either be displayed using imported images or by importing a custom modified Opentype font that uses DSUB letter substitutions to display whatever you want to the user. It could be convincing I'm guessing in some cases.

**Comment by hackvertor** [comment]
Hi Ian thanks for raising this issue. You're right abusing AngularJS could solve this impossible lab but I don't think CSS has anything to do with it. AngularJS processes {{}} anywhere within HTML tags so I think that's what you are seeing rather than CSS after selectors causing evaluation of the template. For example:

https://portswigger-labs.net/xss/angularjs.php?version=1.6.0&x=%3Clink%20href=//subdomain1.portswigger-labs.net/xss/angularjs.css%20rel=stylesheet%3E%3Ch1%3Etest

You can see that the after selector is active and the pseudo element appears but this does not cause JavaScript execution. Please prove me wrong though as this would be a very cool vector similar impact to CSS expressions back in the day.

I agree that CSS can be harmful and I've done multiple post on that in the past, the most recent was exploiting Ublock Origin:
https://portswigger.net/research/ublock-i-exfiltrate-exploiting-ad-blockers-with-css

But the impossible labs are mainly for XSS exploitation. Thanks very much for your input. Cheers

**Comment by wtconsulting** [comment]
@hackvertor Thanks for the reply! The ::after content was just for demo. I think I was obscuring my own point. Def agree that the Angular is evaled where it is in the HTML and not explicitly related to the CSS. I'm suggesting using the CSS @import to get the stylesheet that contains the Angular because otherwise you don't have access to _equals_ due to the constraint of the lab which means you can't break out of many versions of Angular, and can't do as much with your JS. If the innerHTML in within the scope of AngularJS, and you @import CSS that contains AngularJS (including using equals) which then gets executed as part of the style tag- then you have JS context, that was all my point was. How else would you get use of equals without importing it from somewhere other than the url? I couldn't think of a way. Cheers mate!

**Comment by hackvertor** [comment]
You can just HTML encode the equal:

https://portswigger-labs.net/xss/angularjs.php?type=reflected&csp=0&version=1.4.0&x=%7B%7B%27a%27.constructor.prototype.charAt%26%23x3D%5B%5D.join%3B%24eval%28%27x%26%23x3D1%7D%20%7D%20%7D%3Balert%281%29%2F%2F%27%29%3B%7D%7D
