### ISSUE TITLE
RPO with PDF / Anchor Download

### ISSUE THREAD

**Issue by wtconsulting** [PortSwigger/xss-cheatsheet-data#59]

**Comment by hackvertor** [comment]
This is seriously good research and I hadn't even considered RPO for PDFS! I'd suggest deleting this issue because you could use it for a talk for sure. Maybe you could combine this with embedding data inside the PDF or some form of dangling markup not sure how though. I'd suggest contacting Ange Albertini he'd love this and this is right up his street.

**Comment by wtconsulting** [comment]
@hackvertor Thanks for the feedback! I can't delete this but feel free!

**Comment by hackvertor** [comment]
Hi Ian, please can you contact me on Twitter/LinkedIn to discuss this. Thanks.
